apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
spec:
  replicas: 1 # HA uchun odatda StatefulSet ishlatiladi, lekin Docker-compose dagi kabi oddiyroq ko'rinishda:
  selector:
    matchLabels:
      service: postgres-db
  template:
    metadata:
      labels:
        service: postgres-db
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: "onlyoffice"
        - name: POSTGRES_USER
          value: "onlyoffice"
        - name: POSTGRES_PASSWORD
          value: "KUCHLI_PAROL_YOZING"
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster-svc
spec:
  selector:
    service: postgres-db
  ports:
  - port: 5432
    targetPort: 5432
