global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'onlyoffice'
    static_configs:
      - targets: ['statsd_exporter:9102']



  - job_name: 'webapi'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['webapi:8080']
        labels:
          application: 'webapi'


  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: 'prometheus'

    static_configs:
      - targets: ['localhost:9090']
